param (
    [ValidateSet('Release', 'Debug')][string]$BuildType = 'Release',
    [string]$UCP3Path = ''
)

$ErrorActionPreference = 'Stop'
# UCP already runs PowerShell. No additional interpreter or packages are needed.
# This manifest also owns the file selection for standalone preview ZIPs.
$rules = Get-Content -LiteralPath "$PSScriptRoot/package-files.json" -Raw | ConvertFrom-Json
if ($rules.format -ne 1) { throw 'Unsupported recorder package manifest' }
$source = [IO.Path]::GetFullPath($PSScriptRoot)
$stage = [IO.Path]::GetFullPath((Join-Path $source 'dist/store'))
if (-not $stage.StartsWith("$source\dist\", [StringComparison]::OrdinalIgnoreCase)) {
    throw 'Store staging directory must remain inside the source tree'
}
foreach ($path in @((Join-Path $source 'dist'), $stage)) {
    if ((Test-Path -LiteralPath $path) -and ((Get-Item -LiteralPath $path).Attributes -band [IO.FileAttributes]::ReparsePoint)) {
        throw 'Store staging cannot follow directory links'
    }
}
$files = @($rules.required)
foreach ($tree in $rules.trees) {
    $files += Get-ChildItem -LiteralPath (Join-Path $source $tree[0]) -Filter $tree[1] -Recurse -File |
        ForEach-Object { $_.FullName.Substring($source.Length + 1).Replace('\', '/') }
}
$files += $rules.optional | Where-Object { Test-Path -LiteralPath (Join-Path $source $_) }
if ($BuildType -eq 'Release') { $files = $files | Where-Object { $_ -notin $rules.diagnosticFiles } }
foreach ($name in $files) {
    $path = [IO.Path]::GetFullPath((Join-Path $source $name))
    if (-not $path.StartsWith("$source\", [StringComparison]::OrdinalIgnoreCase) -or
        -not (Test-Path -LiteralPath $path -PathType Leaf) -or
        ((Get-Item -LiteralPath $path).Attributes -band [IO.FileAttributes]::ReparsePoint)) {
        throw "Invalid recorder package member: $name"
    }
}
if (Test-Path -LiteralPath $stage) { Remove-Item -LiteralPath $stage -Recurse -Force }
New-Item -ItemType Directory -Path $stage | Out-Null
$utf8 = New-Object System.Text.UTF8Encoding($false)
foreach ($name in $files) {
    $target = Join-Path $stage $name
    New-Item -ItemType Directory -Force -Path ([IO.Path]::GetDirectoryName($target)) | Out-Null
    if ($name -eq 'code/build-profile.lua') {
        $enabled = if ($BuildType -eq 'Debug') { 'true' } else { 'false' }
        $text = "-- Generated by the trusted recorder packager.`nreturn {diagnostics=$enabled}`n"
        [IO.File]::WriteAllText($target, $text, $utf8)
    } elseif ($name -eq 'options.yml' -and $BuildType -eq 'Release') {
        $text = [IO.File]::ReadAllText((Join-Path $source $name)).Replace("`r`n", "`n")
        $options = ($rules.diagnosticOptions | ForEach-Object { [regex]::Escape($_) }) -join '|'
        $text = [regex]::Replace($text, "(?ms)^- url: recorder\.(?:$options)\s*\n.*?(?=^- url:|\z)", '')
        [IO.File]::WriteAllText($target, $text, $utf8)
    } else {
        Copy-Item -LiteralPath (Join-Path $source $name) -Destination $target
    }
}
Write-Output $stage
