"""Build recorder data/source packages without executing code from the source tree."""
from dataclasses import dataclass
import hashlib
import json
from pathlib import Path
import re
import zipfile


@dataclass(frozen=True)
class ModulePackage:
    path: Path
    version: str
    sha256: str


DIAGNOSTIC_MODULES = frozenset({
    'rng-attribution.lua', 'rng-observer.lua', 'rng-fire-context.lua', 'rng-spawn-context.lua',
    'attribution-patterns.lua',
})

# Frozen fallback for publishing older PR stages that predate the shared manifest.
LEGACY_FILES = dict(format=1,
    required=['definition.yml', 'options.yml', 'init.lua', 'README.md', 'CHANGELOG.md'],
    trees=[['code', '*.lua'], ['docs', '*.md'], ['docs/images', '*.jpg'], ['locale', '*.yml'], ['locale', '*.md']],
    optional=['tools/compare_multiplayer.py', 'tools/inspect_replay.py'],
    diagnosticFiles=['code/' + name for name in DIAGNOSTIC_MODULES] + ['tools/compare_multiplayer.py', 'tools/inspect_replay.py'],
    diagnosticOptions=['singleplayerRngDiagnostics', 'multiplayerDiagnostics', 'multiplayerDiagnosticsStartTick', 'multiplayerDiagnosticsEndTick'])


def build_module(source: Path, destination: Path, *, profile: str | None = None) -> ModulePackage:
    if profile not in (None, 'release', 'diagnostic'):
        raise ValueError('Unknown recorder build profile')
    source = source.resolve()
    if profile and not (source / 'code' / 'build-profile.lua').is_file():
        raise ValueError('Source does not support separate build profiles')
    definition_path = source / 'definition.yml'
    if definition_path.is_symlink() or not definition_path.resolve().is_relative_to(source):
        raise ValueError('Module definition is outside the source tree')
    definition = definition_path.read_text(encoding='utf-8')
    if not re.search(r'^name: recorder\s*$', definition, re.M):
        raise ValueError('Unexpected module identity')
    match = re.search(r'^version: (\d+\.\d+\.\d+)\s*$', definition, re.M)
    if not match:
        raise ValueError('Invalid recorder version')
    version = match.group(1)
    manifest = source / 'package-files.json'
    if manifest.is_symlink() or not manifest.resolve().is_relative_to(source):
        raise ValueError('Package manifest is outside the source tree')
    rules = json.loads(manifest.read_text(encoding='utf-8')) if manifest.exists() else LEGACY_FILES
    if rules['format'] != 1:
        raise ValueError('Unsupported recorder package manifest')
    files = [source / name for name in rules['required']]
    for folder, pattern in rules['trees']:
        files.extend(sorted((source / folder).rglob(pattern)))
    for name in rules['optional']:
        tool = source / name
        if tool.exists():
            files.append(tool)
    if profile == 'release':
        files = [path for path in files if path.relative_to(source).as_posix() not in rules['diagnosticFiles']]
    # Validate the complete member list before creating an archive. This also
    # rejects directory links that resolve outside the trusted source root.
    for path in files:
        if not path.is_file() or path.is_symlink() or not path.resolve().is_relative_to(source):
            raise ValueError('Package member is missing or outside the source tree: ' + str(path))
    destination.mkdir(parents=True, exist_ok=True)
    asset = destination / f'recorder-{version}.zip'
    with zipfile.ZipFile(asset, 'w', zipfile.ZIP_DEFLATED) as archive:
        for path in files:
            name = path.relative_to(source).as_posix()
            if profile and name == 'code/build-profile.lua':
                enabled = 'true' if profile == 'diagnostic' else 'false'
                archive.writestr(name, f'-- Generated by the trusted recorder packager.\nreturn {{diagnostics={enabled}}}\n')
            elif profile == 'release' and name == 'options.yml':
                options = path.read_text(encoding='utf-8')
                # Preserve the source schema/text for every real playback option.
                # Blocks are top-level '- url:' entries in the module format.
                diagnostic_options = '|'.join(re.escape(name) for name in rules['diagnosticOptions'])
                options = re.sub(r'^- url: recorder\.(?:' + diagnostic_options + r')\s*\n.*?(?=^- url:|\Z)',
                                 '', options, flags=re.M | re.S)
                archive.writestr(name, options)
            else:
                archive.write(path, name)
    with zipfile.ZipFile(asset) as archive:
        if archive.testzip() is not None:
            raise ValueError('Recorder package CRC mismatch')
    return ModulePackage(asset, version, hashlib.sha256(asset.read_bytes()).hexdigest())


def build_diagnostic_bundle(source: Path, destination: Path) -> ModulePackage:
    """The outer asset has a distinct name; its inner ZIP has UCP's exact identity."""
    from tempfile import TemporaryDirectory
    with TemporaryDirectory() as temporary:
        module = build_module(source, Path(temporary), profile='diagnostic')
        destination.mkdir(parents=True, exist_ok=True)
        asset = destination / f'recorder-{module.version}-diagnostics-bundle.zip'
        with zipfile.ZipFile(asset, 'w', zipfile.ZIP_DEFLATED) as archive:
            archive.write(module.path, module.path.name)
            archive.writestr('README.txt',
                'Diagnostic build: extract this bundle, then install the inner recorder ZIP through UCP.\n'
                'Install either release or diagnostic, never both. Keep the inner filename unchanged.\n'
                'Optional RNG diagnostics are off by default; enable them only for a targeted investigation.\n'
                'Both builds retain automatic recording, offline playback, controls and integrity checks.\n'
                'Their exact package fingerprints differ: use the recorded build when reproducing a replay.\n')
            archive.writestr(module.path.name + '.sha256', f'{module.sha256}  {module.path.name}\n')
        return ModulePackage(asset, module.version, hashlib.sha256(asset.read_bytes()).hexdigest())
